# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -id {Project 1-21}  -string {{CRITICAL WARNING: [Project 1-21] Could not resolve ISE project part 'xc6slx16-2-ftg256'. Part replaced with default 'xc7k70tfbv676-1'.}}  -suppress 
set_msg_config  -id {Project 1-467}  -string {{CRITICAL WARNING: [Project 1-467] UCF constraints are not supported in Vivado (src/zxuno_lx16.ucf). Please convert these constraints to XDC and add then add the converted XDC constraints file to the project.}}  -suppress 
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/repos/a35/NUEVO/arkanoid/A35/A35.cache/wt [current_project]
set_property parent.project_path F:/repos/a35/NUEVO/arkanoid/A35/A35.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/repos/a35/defender/a35t/a35t.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/repos/a35/NUEVO/arkanoid/src/modulo_top_a35t.v
  F:/repos/a35/NUEVO/arkanoid/src/multiboot_artix7.v
  F:/repos/a35/NUEVO/arkanoid/src/rtl_mio/ps2mouse.v
}
read_vhdl -library xil_defaultlib {
  F:/repos/a35/NUEVO/arkanoid/src/rtl_mio/keyb/ps2_intf.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl_mio/keyb/keyboard.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl_mio/line_doubler.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl_mio/dac.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/color_prom_2.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/color_prom_3.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/arkanoid.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/color_prom_1.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/eprom_3.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/eprom_5.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/eprom_4.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls174.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls74.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/cmos_4584.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls161.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls00.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls32.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls157.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls374.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls298.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls27.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls155.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls20.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls08.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls273.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls139.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls669.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls04.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls86.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls393.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls244.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls283.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/logic/ls257.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/T80/T80_Pack.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/T80/T80s.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/T80/T80_ALU.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/T80/T80.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/T80/T80_MCode.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/T80/T80_Reg.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/spram_en.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/spram.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/sound/vol_table.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/custom/mb112s146.vhd
  F:/repos/a35/NUEVO/arkanoid/src/rtl/sound/ym2149.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/eprom_1_taito.vhd
  F:/repos/a35/NUEVO/arkanoid/src/roms/eprom_2_taito.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/repos/a35/NUEVO/arkanoid/pines_zxuno_a35t.xdc
set_property used_in_implementation false [get_files F:/repos/a35/NUEVO/arkanoid/pines_zxuno_a35t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top arkanoid_top -part xc7a35tftg256-1 -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef arkanoid_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file arkanoid_top_utilization_synth.rpt -pb arkanoid_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
