# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes.xci
# IP: The module: 'relojes' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'relojes'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes.xdc
# XDC: The top module name and the constraint reference have the same name: 'relojes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'relojes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes.xci
# IP: The module: 'relojes' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'relojes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes.xdc
# XDC: The top module name and the constraint reference have the same name: 'relojes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'relojes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
