# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/jammaZX1/-hw ckong/ckong/A35/A35.cache/wt} [current_project]
set_property parent.project_path {F:/jammaZX1/-hw ckong/ckong/A35/A35.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {f:/jammaZX1/-hw ckong/ckong/A35/A35.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {F:/jammaZX1/-hw ckong/ckong/src/synchro.v}
  {F:/jammaZX1/-hw ckong/ckong/src/multiboot_1x.v}
  {F:/jammaZX1/-hw ckong/ckong/src/modulo_top_a35t.v}
}
read_vhdl -library xil_defaultlib {
  {F:/jammaZX1/-hw ckong/ckong/src/rtl_T80/T80_Reg.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/rtl_T80/T80_Pack.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/rtl_T80/T80_MCode.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/rtl_T80/T80_ALU.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/ym_2149_linmix.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/rtl_T80/T80.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_samples.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/video_gen.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/rtl_T80/T80s.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_tile_bit1.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_tile_bit0.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_program.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_palette.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_big_sprite_tile_bit1.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_big_sprite_tile_bit0.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/roms/ckong_big_sprite_palette.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/line_doubler.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/keyb/ps2_intf.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/gen_ram.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/debounce.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/dac.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/ckong_sound.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/ckong.vhd}
  {F:/jammaZX1/-hw ckong/ckong/src/keyb/keyboard.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{F:/jammaZX1/-hw ckong/ckong/pines_zxuno_a35t.xdc}}
set_property used_in_implementation false [get_files {{F:/jammaZX1/-hw ckong/ckong/pines_zxuno_a35t.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ckong_top -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ckong_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ckong_top_utilization_synth.rpt -pb ckong_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
