# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/repos/a35/NUEVO/mpatrol/A35/A35.cache/wt [current_project]
set_property parent.project_path F:/repos/a35/NUEVO/mpatrol/A35/A35.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo f:/repos/a35/NUEVO/mpatrol/A35/A35.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpb-1.3n.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpe-5.3e.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpb-2.3m.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpe-4.3f.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpe-3.3h.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpa-4.3j.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpa-2.3l.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpa-1.3m.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpe-1.3l.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpe-2.3k.mem
  F:/repos/a35/NUEVO/mpatrol/src/roms/mpa-3.3k.mem
}
read_verilog -library xil_defaultlib {
  F:/repos/a35/NUEVO/mpatrol/src/rtl/sprom.v
  F:/repos/a35/NUEVO/mpatrol/src/rtl/spram.v
  F:/repos/a35/NUEVO/mpatrol/src/rtl/dprom_2r.v
  F:/repos/a35/NUEVO/mpatrol/src/rtl/dpram.v
  F:/repos/a35/NUEVO/mpatrol/src/rtl/scandoubler.v
  F:/repos/a35/NUEVO/mpatrol/src/multiboot_1x.v
  F:/repos/a35/NUEVO/mpatrol/src/modulo_top_lx35.v
}
read_vhdl -library xil_defaultlib {
  F:/repos/a35/NUEVO/mpatrol/src/rtl/target_pkg.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/bitmapctl_e.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/video_controller_pkg.vhd
  F:/repos/a35/NUEVO/mpatrol/src/t80/T80_Pack.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/video_controller_pkg_body.vhd
  F:/repos/a35/NUEVO/mpatrol/src/t80/T80_Reg.vhd
  F:/repos/a35/NUEVO/mpatrol/src/t80/T80_MCode.vhd
  F:/repos/a35/NUEVO/mpatrol/src/t80/T80_ALU.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/sprite_pkg.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/pace_pkg.vhd
  F:/repos/a35/NUEVO/mpatrol/src/t80/T80.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/sprite_pkg_body.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/platform_variant_pkg.vhd
  F:/repos/a35/NUEVO/mpatrol/src/t80/T80se.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/spritereg.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/spritectl.vhd
  F:/repos/a35/NUEVO/mpatrol/src/t80/Z80.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/video_mixer.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/video_controller.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/tilemapctl.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/sprite_array.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/input_mapper.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/clk_div.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/bitmap3_ctl.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/bitmap2_ctl.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/bitmap1_ctl.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/YM2149_linmix_sep.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/platform.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/moon_patrol_sound_prog.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/Inputs.VHD
  F:/repos/a35/NUEVO/mpatrol/src/rtl/Graphics.VHD
  F:/repos/a35/NUEVO/mpatrol/src/rtl/gen_ram.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/cpu68.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/pace.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/moon_patrol_sound_board.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/dac.vhd
  F:/repos/a35/NUEVO/mpatrol/src/keyb/ps2_intf.vhd
  F:/repos/a35/NUEVO/mpatrol/src/rtl/mpatrol.vhd
  F:/repos/a35/NUEVO/mpatrol/src/keyb/keyboard.vhd
}
read_ip -quiet F:/repos/a35/NUEVO/mpatrol/A35/A35.srcs/sources_1/ip/relojes/relojes.xci
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/mpatrol/A35/A35.srcs/sources_1/ip/relojes/relojes_board.xdc]
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/mpatrol/A35/A35.srcs/sources_1/ip/relojes/relojes.xdc]
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/mpatrol/A35/A35.srcs/sources_1/ip/relojes/relojes_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/repos/a35/NUEVO/mpatrol/pines_zxuno_a35t.xdc
set_property used_in_implementation false [get_files F:/repos/a35/NUEVO/mpatrol/pines_zxuno_a35t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mpatrol_top -part xc7a35tftg256-1 -directive RuntimeOptimized


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mpatrol_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mpatrol_top_utilization_synth.rpt -pb mpatrol_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
