# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/repos/a35/NUEVO/bagman/A35/A35.cache/wt [current_project]
set_property parent.project_path F:/repos/a35/NUEVO/bagman/A35/A35.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/repos/a35/NUEVO/bagman/A35/A35.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/repos/a35/NUEVO/bagman/src/synchro.v
  F:/repos/a35/NUEVO/bagman/src/multiboot_artix7.v
  F:/repos/a35/NUEVO/bagman/src/modulo_top_a35t.v
}
read_vhdl -library xil_defaultlib {
  F:/repos/a35/NUEVO/bagman/src/rtl_T80/T80_RegX.vhd
  F:/repos/a35/NUEVO/bagman/src/rtl_T80/T80_Pack.vhd
  F:/repos/a35/NUEVO/bagman/src/rtl_T80/T80_MCode.vhd
  F:/repos/a35/NUEVO/bagman/src/rtl_T80/T80_ALU.vhd
  F:/repos/a35/NUEVO/bagman/src/rtl_T80/T80.vhd
  F:/repos/a35/NUEVO/bagman/src/roms/bagman_speech2.vhd
  F:/repos/a35/NUEVO/bagman/src/roms/bagman_speech1.vhd
  F:/repos/a35/NUEVO/bagman/src/plc10_speech_synthetizer.vhd
  F:/repos/a35/NUEVO/bagman/src/ym_2149_linmix.vhd
  F:/repos/a35/NUEVO/bagman/src/video_gen.vhd
  F:/repos/a35/NUEVO/bagman/src/rtl_T80/T80s.vhd
  F:/repos/a35/NUEVO/bagman/src/roms/bagman_tile_bit1.vhd
  F:/repos/a35/NUEVO/bagman/src/roms/bagman_tile_bit0.vhd
  F:/repos/a35/NUEVO/bagman/src/roms/bagman_program.vhd
  F:/repos/a35/NUEVO/bagman/src/roms/bagman_palette.vhd
  F:/repos/a35/NUEVO/bagman/src/line_doubler.vhd
  F:/repos/a35/NUEVO/bagman/src/keyb/ps2_intf.vhd
  F:/repos/a35/NUEVO/bagman/src/gen_ram.vhd
  F:/repos/a35/NUEVO/bagman/src/debounce.vhd
  F:/repos/a35/NUEVO/bagman/src/dac.vhd
  F:/repos/a35/NUEVO/bagman/src/bagman_speech.vhd
  F:/repos/a35/NUEVO/bagman/src/bagman_pal16r6.vhd
  F:/repos/a35/NUEVO/bagman/src/keyb/keyboard.vhd
  F:/repos/a35/NUEVO/bagman/src/bagman.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/repos/a35/NUEVO/bagman/pines_zxuno_a35t.xdc
set_property used_in_implementation false [get_files F:/repos/a35/NUEVO/bagman/pines_zxuno_a35t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bagman_top -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bagman_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bagman_top_utilization_synth.rpt -pb bagman_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
