# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config  -id {Vivado 12-3481}  -string {{ERROR: [Vivado 12-3481] Cannot replace a file with itself: 'F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/c64_zx3.vhd'}}  -suppress 
set_msg_config  -id {Project 1-21}  -string {{CRITICAL WARNING: [Project 1-21] Could not resolve ISE project part 'xc6slx16-2-ftg256'. Part replaced with default 'xc7k70tfbv676-1'.}}  -suppress 
set_msg_config  -id {Project 1-467}  -string {{CRITICAL WARNING: [Project 1-467] UCF constraints are not supported in Vivado (pines_zxuno_lx16.ucf). Please convert these constraints to XDC and add then add the converted XDC constraints file to the project.}}  -suppress 
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.cache/wt [current_project]
set_property parent.project_path F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid8580/sid_envelope.v
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid8580/sid_voice.v
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid8580/sid_filters.v
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid8580/sid8580.v
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/sigma_delta_dac.v
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/sdram.v
}
read_vhdl -library xil_defaultlib {
  F:/repos/a35/NUEVO/comodore64_beta_7/src/roms/sprom_jiffy.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/roms/rom_jiffy_kernal.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/t65/T65_Pack.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/t65/T65_MCode.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/t65/T65_ALU.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/sid_debug_pkg.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/Q_table.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/my_math_pkg.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/t65/T65.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/wave_map.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/sid_regs.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/sid_mixer.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/sid_filter.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/sid_ctrl.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/oscillator.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/mult_acc.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/adsr_multi.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/roms/sprom_c1541.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/roms/rom_c64_kernal.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/roms/rom_c64_chargen.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/roms/rom_c64_basic.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/ZPUFlex/RTL/zpupkg.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/CharROM/CharROM_ROM.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/gen_rwram.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c1541/c1541_m6522.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/sid/sid_top.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/ZPUFlex/RTL/zpu_core_flex.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/RTL/spi.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/RTL/OnScreenDisplay.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/RTL/io_ps2_com.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/RTL/interrupt_controller.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/Firmware/CtrlROM_ROM.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/video_vicII_656x.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/gen_ram.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/fpga64_scandoubler.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/fpga64_rgbcolor.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/fpga64_keyboard.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/fpga64_buslogic_roms_mmu.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/cpu_6510.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/cia6526.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c1541/gcr_floppy.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c1541/c1541_logic.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/RTL/OSD_Overlay.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/CtrlModule/CtrlModule/RTL/CtrlModule.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/ps2_intf.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/fpga64_sid_iec.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/composite_sync.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c1541/c1541_sd.vhd
  F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/c64_zx3.vhd
}
read_ip -quiet F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes.xci
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes_board.xdc]
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes.xdc]
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes_ooc.xdc]

read_ip -quiet F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block.xci
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/repos/a35/NUEVO/comodore64_beta_7/pines_zxuno_a35t.xdc
set_property used_in_implementation false [get_files F:/repos/a35/NUEVO/comodore64_beta_7/pines_zxuno_a35t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top c64_zx3 -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef c64_zx3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file c64_zx3_utilization_synth.rpt -pb c64_zx3_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
