# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block.xci
# IP: The module: 'DualPortRAM_Block' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DualPortRAM_Block'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block.xci
# IP: The module: 'DualPortRAM_Block' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DualPortRAM_Block'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
