# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Vivado 12-3481}  -string {{ERROR: [Vivado 12-3481] Cannot replace a file with itself: 'F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/c64_zx3.vhd'}}  -suppress 
set_msg_config  -id {Project 1-21}  -string {{CRITICAL WARNING: [Project 1-21] Could not resolve ISE project part 'xc6slx16-2-ftg256'. Part replaced with default 'xc7k70tfbv676-1'.}}  -suppress 
set_msg_config  -id {Project 1-467}  -string {{CRITICAL WARNING: [Project 1-467] UCF constraints are not supported in Vivado (pines_zxuno_lx16.ucf). Please convert these constraints to XDC and add then add the converted XDC constraints file to the project.}}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.cache/wt [current_project]
set_property parent.project_path F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block.xci
set_property used_in_implementation false [get_files -all f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/DualPortRAM_Block_synth_1 -new_name DualPortRAM_Block -ip [get_ips DualPortRAM_Block]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top DualPortRAM_Block -part xc7a35tftg256-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix DualPortRAM_Block_ DualPortRAM_Block.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ DualPortRAM_Block_stub.v
 lappend ipCachedFiles DualPortRAM_Block_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ DualPortRAM_Block_stub.vhdl
 lappend ipCachedFiles DualPortRAM_Block_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ DualPortRAM_Block_sim_netlist.v
 lappend ipCachedFiles DualPortRAM_Block_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ DualPortRAM_Block_sim_netlist.vhdl
 lappend ipCachedFiles DualPortRAM_Block_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp DualPortRAM_Block.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips DualPortRAM_Block]
}

rename_ref -prefix_all DualPortRAM_Block_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DualPortRAM_Block.dcp
create_report "DualPortRAM_Block_synth_1_synth_report_utilization_0" "report_utilization -file DualPortRAM_Block_utilization_synth.rpt -pb DualPortRAM_Block_utilization_synth.pb"

if { [catch {
  file copy -force F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/DualPortRAM_Block_synth_1/DualPortRAM_Block.dcp f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/DualPortRAM_Block_synth_1/DualPortRAM_Block.dcp f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/DualPortRAM_Block_synth_1/DualPortRAM_Block_stub.v f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/DualPortRAM_Block_synth_1/DualPortRAM_Block_stub.vhdl f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/DualPortRAM_Block_synth_1/DualPortRAM_Block_sim_netlist.v f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/DualPortRAM_Block_synth_1/DualPortRAM_Block_sim_netlist.vhdl f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.ip_user_files/ip/DualPortRAM_Block]} {
  catch { 
    file copy -force f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_stub.v F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.ip_user_files/ip/DualPortRAM_Block
  }
}

if {[file isdir F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.ip_user_files/ip/DualPortRAM_Block]} {
  catch { 
    file copy -force f:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block_stub.vhdl F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.ip_user_files/ip/DualPortRAM_Block
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
