# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Project 1-467}  -string {{CRITICAL WARNING: [Project 1-467] UCF constraints are not supported in Vivado (pines_zxuno_lx16.ucf). Please convert these constraints to XDC and add then add the converted XDC constraints file to the project.}}  -suppress 
set_msg_config  -id {Project 1-21}  -string {{CRITICAL WARNING: [Project 1-21] Could not resolve ISE project part 'xc6slx16-2-ftg256'. Part replaced with default 'xc7k70tfbv676-1'.}}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
set_msg_config  -id {Synth 8-439}  -string {{ERROR: [Synth 8-439] module 'bombjack_top' not found}}  -suppress 
set_msg_config  -id {Common 17-55}  -string {{CRITICAL WARNING: [Common 17-55] 'set_property' expects at least one object. [F:/repos/a35/bombjack/pines_zxuno_a35t.xdc:63]
Resolution: If [get_<value>] was used to populate the object, check to make sure this command returns at least one valid object.}}  -suppress 
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/repos/a35/NUEVO/bombjack/A35/A35.cache/wt [current_project]
set_property parent.project_path F:/repos/a35/NUEVO/bombjack/A35/A35.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/repos/a35/NUEVO/bombjack/A35/A35.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/repos/a35/NUEVO/bombjack/source/modulo_top_a35t.v
  F:/repos/a35/NUEVO/bombjack/source/multiboot_artix7.v
}
read_vhdl -library xil_defaultlib {
  F:/repos/a35/NUEVO/bombjack/source/bombjack/T80/T80_Pack.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/T80/T80_RegX.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/T80/T80_MCode.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/T80/T80_ALU.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/T80/T80.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/ym2149/YM2149_linmix.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/T80/T80sed.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/sprite_buff.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_3H.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_1R.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_1N.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_1M.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_1L.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_1J.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/scan_converter.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_8R.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_8N.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_8L.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_8K.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_8H.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_8E.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_7M.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_7L.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_7J.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/roms/ROM_4P.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/prog_roms_ramb.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p9_audio_cpu.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p7_bgnd_tiles.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p6_char_gen.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p5_overlay.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p4_sprites.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p3_timing.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p2_switches.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p10_psgs.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/keyb/ps2_intf.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/debounce.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/dac.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/keyb/keyboard.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/bombjack.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/p8_palette_no_brams.vhd
  F:/repos/a35/NUEVO/bombjack/source/bombjack/composite_sync.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/repos/a35/NUEVO/bombjack/pines_zxuno_a35t.xdc
set_property used_in_implementation false [get_files F:/repos/a35/NUEVO/bombjack/pines_zxuno_a35t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top bombjack_top -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bombjack_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bombjack_top_utilization_synth.rpt -pb bombjack_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
