# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -id {Vivado 12-3481}  -string {{ERROR: [Vivado 12-3481] Cannot replace a file with itself: 'F:/repos/a35/NUEVO/comodore64_beta_7/src/c64/c64_zx3.vhd'}}  -suppress 
set_msg_config  -id {Project 1-21}  -string {{CRITICAL WARNING: [Project 1-21] Could not resolve ISE project part 'xc6slx16-2-ftg256'. Part replaced with default 'xc7k70tfbv676-1'.}}  -suppress 
set_msg_config  -id {Project 1-467}  -string {{CRITICAL WARNING: [Project 1-467] UCF constraints are not supported in Vivado (pines_zxuno_lx16.ucf). Please convert these constraints to XDC and add then add the converted XDC constraints file to the project.}}  -suppress 

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param xicom.use_bs_reader 1
  create_project -in_memory -part xc7a35tftg256-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.cache/wt [current_project]
  set_property parent.project_path F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.xpr [current_project]
  set_property ip_output_repo F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.runs/synth_1/c64_zx3.dcp
  read_ip -quiet F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/relojes/relojes.xci
  read_ip -quiet F:/repos/a35/NUEVO/comodore64_beta_7/A35/A35.srcs/sources_1/ip/DualPortRAM_Block/DualPortRAM_Block.xci
  read_xdc F:/repos/a35/NUEVO/comodore64_beta_7/pines_zxuno_a35t.xdc
  link_design -top c64_zx3 -part xc7a35tftg256-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force c64_zx3_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file c64_zx3_drc_opted.rpt -pb c64_zx3_drc_opted.pb -rpx c64_zx3_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force c64_zx3_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file c64_zx3_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file c64_zx3_utilization_placed.rpt -pb c64_zx3_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file c64_zx3_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force c64_zx3_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file c64_zx3_drc_routed.rpt -pb c64_zx3_drc_routed.pb -rpx c64_zx3_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file c64_zx3_methodology_drc_routed.rpt -pb c64_zx3_methodology_drc_routed.pb -rpx c64_zx3_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file c64_zx3_power_routed.rpt -pb c64_zx3_power_summary_routed.pb -rpx c64_zx3_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file c64_zx3_route_status.rpt -pb c64_zx3_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file c64_zx3_timing_summary_routed.rpt -pb c64_zx3_timing_summary_routed.pb -rpx c64_zx3_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file c64_zx3_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file c64_zx3_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file c64_zx3_bus_skew_routed.rpt -pb c64_zx3_bus_skew_routed.pb -rpx c64_zx3_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force c64_zx3_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force c64_zx3.mmi }
  write_bitstream -force c64_zx3.bit 
  catch {write_debug_probes -quiet -force c64_zx3}
  catch {file copy -force c64_zx3.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

