# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/repos/a35/NUEVO/pleiads/a35/a35.cache/wt [current_project]
set_property parent.project_path F:/repos/a35/NUEVO/pleiads/a35/a35.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo f:/repos/a35/NUEVO/pleiads/a35/a35.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/repos/a35/NUEVO/pleiads/src/scandoubler.v
  F:/repos/a35/NUEVO/pleiads/src/multiboot_1x.v
  F:/repos/a35/NUEVO/pleiads/src/modulo_top_a35.v
  F:/repos/a35/NUEVO/pleiads/src/synchro.v
}
read_vhdl -library xil_defaultlib {
  F:/repos/a35/NUEVO/pleiads/src/cpu/T80_Reg.vhd
  F:/repos/a35/NUEVO/pleiads/src/cpu/T80_Pack.vhd
  F:/repos/a35/NUEVO/pleiads/src/cpu/T80_MCode.vhd
  F:/repos/a35/NUEVO/pleiads/src/cpu/T80_ALU.vhd
  F:/repos/a35/NUEVO/pleiads/src/cpu/T80.vhd
  F:/repos/a35/NUEVO/pleiads/src/ROM/prom_palette_ic41.vhd
  F:/repos/a35/NUEVO/pleiads/src/ROM/prom_palette_ic40.vhd
  F:/repos/a35/NUEVO/pleiads/src/ROM/prom_ic40.vhd
  F:/repos/a35/NUEVO/pleiads/src/ROM/prom_ic39.vhd
  F:/repos/a35/NUEVO/pleiads/src/ROM/prom_ic24.vhd
  F:/repos/a35/NUEVO/pleiads/src/ROM/prom_ic23.vhd
  F:/repos/a35/NUEVO/pleiads/src/ROM/pleiads_prog.vhd
  F:/repos/a35/NUEVO/pleiads/src/phoenix_video.vhd
  F:/repos/a35/NUEVO/pleiads/src/phoenix_music.vhd
  F:/repos/a35/NUEVO/pleiads/src/phoenix_effect3.vhd
  F:/repos/a35/NUEVO/pleiads/src/phoenix_effect2.vhd
  F:/repos/a35/NUEVO/pleiads/src/phoenix_effect1.vhd
  F:/repos/a35/NUEVO/pleiads/src/gen_ram.vhd
  F:/repos/a35/NUEVO/pleiads/src/cpu/T8080se.vhd
  F:/repos/a35/NUEVO/pleiads/src/phoenix.vhd
  F:/repos/a35/NUEVO/pleiads/src/keyb/ps2_intf.vhd
  F:/repos/a35/NUEVO/pleiads/src/debounce.vhd
  F:/repos/a35/NUEVO/pleiads/src/dac.vhd
  F:/repos/a35/NUEVO/pleiads/src/phoenix_zxuno.vhd
  F:/repos/a35/NUEVO/pleiads/src/keyb/keyboard.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/repos/a35/NUEVO/pleiads/pines_zxuno_a35t.xdc
set_property used_in_implementation false [get_files F:/repos/a35/NUEVO/pleiads/pines_zxuno_a35t.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top pleiads_top -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pleiads_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file pleiads_top_utilization_synth.rpt -pb pleiads_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
